# Site settings
title: Anton Nedelin
email: anton.nedelin@gmail.com
description: Academic webpage of Anton Nedelin
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Dr. Anton Nedelin<br/>
    Research Associate,<br/>
    <a href="https://www.kcl.ac.uk/research/theoretical-physics" target="_blank">Theoretical Physics Division</a>,<br/>
    <a href="https://www.kcl.ac.uk/mathematics" target="_blank">Department of Mathematics</a>,<br/>
    King's College London

location: >
  King's College London,<br/>
  Strand Building,<br/>
  WC2R 2LS London, Uk

contact: >
    <a href="mailto:anton.nedelin@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Anton via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
# - name: software
# - name: team
  - name: teaching


# Do you want to group your publications by year? {true/false}
group_pub_by_year: true


include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


    #plugins: ['jekyll/scholar']

    #scholar:

    #last_name: Nedelin
    #first_name: Anton

    #style: citesty
    #locale: en

    #source: /assets/
    #bibliography: ref.bib
    #bibliography_template: bibtemplate
    #sort_by: year, month
    #order: descending

    #replace_strings: true
    #join_strings: true

    #details_dir: bibliography
    #details_layout: bibtex.html
    #details_link: Details

    #query: "@*"

    #bibliography_list_attributes:
    #reversed: "reversed"


exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile

